name: Deploy Glue Code

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug OIDC Claims
        shell: bash
        run: |
          TOKEN=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | jq -r '.value')

          echo "$TOKEN" | cut -d '.' -f2 | base64 -d 2>/dev/null \
            | jq '{sub, aud, repository, repository_owner, ref, repository_id, repository_owner_id}'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Upload Glue code to S3
        run: |
          aws s3 cp glue.py s3://vinay-cicd-artifacts-2026/glue.py